name: smartid_flutter
description: SmartId Bridge for Flutter.
version: 1.0.0
homepage:

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: ">=3.19.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.develsystems.smartid.smartid_flutter
        pluginClass: SmartidFlutterPlugin
      ios:
        pluginClass: SmartidFlutterPlugin